version: '2'

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

  rating:
    image: rating:latest
    ports:
      - 8080:8080
    links:
      - mongodb

volumes:
    mongodb-data:
      driver: local
